dist: bionic   # ubuntu 18.04
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  include:
    - python: "3.8"
      env: LONGTESTS=1

  allow_failures:
    - python: "3.8"
      env: LONGTESTS=1
  fast_finish: true


install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover -s tests/
after_success:
  - coveralls