dist: bionic   # ubuntu 18.04
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover -s tests/
after_success:
  - coveralls